configserver:
    name: Docker Consul Service
    status: Connected to Consul Server running in Docker

platform:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
